name: mdbook_utils_ci
services:
  mdbook-utils:
    image: mdbook_utils_ci:${IMAGE_VERSION}  # Name and tag of the image that will be built
    build:
      target: ci
      cache_from:
        - type=gha                           # GitHub Action cache
        #- type=local,dest=./.cache
      cache_to:
        - type=gha,mode=max
        #- type=local,dest=./.cache
    volumes:
      - type: bind
        ## Path where the container will write the book HTML / JS to, on the CI host (provided by GitHub Action)
        ## Source is relative to the Docker Compose file location somehow
        source: ../user_guide_book/
        target: /code/user_guide/book/
        bind:
          create_host_path: true
